### ISSUE TITLE
Korean & Japanese Language Support

### ISSUE THREAD

**Issue by jg-taylor** [mobiledesres/HarmonyOS-Sans#3]
Hi guys,

Is there any Korean and Japanese langauge support for this typeface? I only see TC and SC characters??

If not, how are we applying these characters to Korean and Japanese-speaking demographics? 

Best,
James

**Comment by mobiledesres** [comment]
Currently Harmony OS Sans only supports [Chinese (Simplified & Traditional), Latin, Cyrillic, Greek, and Arabic writings](https://developer.huawei.com/consumer/en/doc/design-guides-V1/font-0000001157868583-V1). There is no support for Japanese and Korean.

**Comment by jg-taylor** [comment]
Hi there,

Is there scope for this to be included in the near future please?


Best,
James


[https://i.ibb.co/njt4gw2/Profile-Image-crop-1.png]
[https://i.ibb.co/4s6SsMW/Copy-of-Gimlett-Taylor-Logo.png]
[facebook]<https://www.facebook.com/gimletttaylor>
[linkedin]<https://www.linkedin.com/in/james-gimlett-taylor/>
[instagram]<https://www.instagram.com/jgtaylor7/>
James Gimlett-Taylor

UI/UX Designer & Typographer

Car Designer | Creative Partner

[mobilePhone]
07769340306
[emailAddress]


***@***.******@***.***>
[website]
www.jg-taylor.com<https://www.jg-taylor.com/>
[address]
Warwickshire, United Kingdom
PORTFOLIO<https://www.jg-taylor.com/>

On 9 Oct 2024, at 07:36, Mobile Design Resources ***@***.***> wrote:

﻿

Currently Harmony OS Sans only supports Chinese (Simplified & Traditional), Latin, Cyrillic, Greek, and Arabic writings<https://developer.huawei.com/consumer/en/doc/design-guides-V1/font-0000001157868583-V1>. There is no support for Japanese and Korean.
